### ISSUE TITLE
Can I select quality of download?

### ISSUE THREAD

**Issue by zabop** [Yharooer/panopto-downloader-chrome#6]
Very cool tool, thanks for uploading it. On the bottom of each panopto page, there is a quality button:
![image](https://user-images.githubusercontent.com/20886570/122561846-9e77c380-d042-11eb-8c68-62bf605f90ff.png)
![image](https://user-images.githubusercontent.com/20886570/122561872-a7689500-d042-11eb-9fc3-fc1c58a80a32.png)
Is there a way to tell to this downloader which quality I prefer?

**Comment by Yharooer** [comment]
Unfortunately there is no way to select the quality at the moment and the chrome extension can only download Panopto's pre-processed 'Podcast forms' of recordings.

I am working on an update which will allow custom downloads which will allow downloading of lectures in full quality [#4]. This should hopefully be available in the next few months.

**Comment by zabop** [comment]
That's great, thank you!
