### ISSUE TITLE
Downloads not working with 2.0.0-dev

### ISSUE THREAD

**Issue by daniel-lerch** [Yharooer/panopto-downloader-chrome#8]
I built Panopto Downloader from source and launched it in Microsoft Edge by `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --load-extension=C:\Users\Admin\source\panopto-downloader-chrome\build` and the extension was loaded. Unfortunately, downloading a video from Panopto did not work. The download progress remained at 0% and I did not see any network usage in task manager.

Does Panopto Downloader print any kind of logs where I can search for the error? The videos from Technische Universität Darmstadt require a login. Can this cause problems with Panopto Downloader even if the session in the browser is valid?

**Comment by Yharooer** [comment]
Yes, the downloads do not work because the current state of Panopto Downloader version 2 is unfinshed. There is no estimated completion date for Panopto Downloader version 2.

**Comment by daniel-lerch** [comment]
Thank you for this fast answer. Is there a way to contribute to this project to help you finishing v2?

**Comment by Yharooer** [comment]
Quite possibly! I have a good idea in what direction to head towards version 2, but unfortunately I don't have the time at the moment (and may not for the foreseeable future) to finish the release. I think there is still quite a lot of work to be done to get to a working release. I'd be happy to collaborate with other developers to move forward on this project, but I haven't really thought much about the best way to do that. If you think you'd be able and willing to contribute, please do send me an email and get in touch; I'd be happy to chat!
