### ISSUE TITLE
Panopto-Video-DL is a currently working panopto downloader

### ISSUE THREAD

**Issue by bekaertruben** [Yharooer/panopto-downloader-chrome#9]
In case you're looking for something to model your v2 on, [Panopto-Video-DL](https://github.com/Panopto-Video-DL/) is currently working, and it's literally less than 200 lines of code total (most of it's hidden in dependencies of course).

This isn't a real issue, you're free to close it. This is just the easiest way to contact you.

**Comment by Yharooer** [comment]
Hi there! I didn't see this issue until today! Thanks for letting me know about this! Sadly I was looking into this a while back but I was finding it very hard to embed FFmpeg in a Chrome Extension using WASM, so was unable to make further progress on this. 😔
